server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moe_oa
    username: root
    password: root

mybatis:
  typeAliasesPackage: com.oa.entity
  mapperLocations: mapper/*.xml
