server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moe_oa
    username: root
    password: root

mybatis:
  typeAliasesPackage: com.oa.entity
  mapperLocations: classpath\:mapper/*.xml
